Milestone 6: Friendships v2
JasemDuncan/ror-social-scaffold pull request #3
Opened 2020-11-27 21:12 UTC by JasemDuncan

For this milestone is required to implement friendships with 2 rows for mutual friendship. 

In this case, we have a method named "confirm_friend(user)", in this method the we create the relation between friends.

The Project Specific in this part is:

As a logged-in user:
  
    I want to be able to accept or reject friendships invitation.

2020-11-27 22:16 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual project, you required to do these changes, listed below:
 
## [REQUIRED CHANGES]

- [ ] You project has 33 examples, 9 failures, please fix the failures;
![image](https://user-images.githubusercontent.com/56762529/100486935-084f7080-30e5-11eb-8cf5-f6f16b2a3b81.png)

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-11-27 23:00 UTC, JasemDuncan commented
Hello @kevincappuccino, I am writing on slack. I have some questions please.

2020-11-27 23:29 UTC, JasemDuncan commented
The testing part should run it one file by one. that is because for the testing file we are using capybara, and the syntax will cause an error in the other testing files that are not using, that is why we have for some testing require 'rails_helper' and 'rails_helper_capybara'.
![imagen](https://user-images.githubusercontent.com/61840552/100488790-485f2500-30de-11eb-88a3-83d25f91aae1.png)

![imagen](https://user-images.githubusercontent.com/61840552/100488800-5a40c800-30de-11eb-9b3f-daeec39a8a3b.png)

Please if there is a way to run all witout having the error about, please give us a hint. Thanks.

2020-11-28 00:01 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [ ] The test suite is still failing, let's fix it.
![1](https://user-images.githubusercontent.com/23278161/100489580-33ea4f00-3115-11eb-80b7-ba8a0f6ed3b5.png)

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-12-01 21:58 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello @KingsleyMcSimon and @JasemDuncan 

You've both done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

In Friendship Version 2, we are going handle friendships a little more different

- [ ] When friendship is confirmed, an additional row with reversed user-friend pair is created
```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

### - [ ] Thanks to this, we can find user friends only by user_id in the friendships table
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

 - [ ] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

 - [ ] In order to get all posts written by a user on their friends, students can use a simple method in User model (in order to NOT do it with Enumerables)
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

#### kindly make the appropriate changes and ask for another code review 👍 

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-12-03 21:54 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team 😃,

**Great job implementing the requested changes 💪. However, there are still a few fixes needed.**

1). **Please add unit tests for your `helpers`**

2). **Check more in the comments below.**

[Optional]

- **You can add tests for your controllers.**

## Happy coding 🥂 

**PS: You can reach me on slack (Rose Wanjohi).**

2020-12-03 21:54 UTC, blackpintz commented on app/models/friendship.rb
> +  # end
Remove the commented code.

2020-12-03 21:54 UTC, blackpintz commented on app/models/post.rb
> +  # end
Remove the commented code.

2020-12-03 21:54 UTC, blackpintz commented on app/models/user.rb
> +  # has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
Remove the commented code.

2020-12-03 21:54 UTC, blackpintz commented on app/models/user.rb
> +  # end
Remove the commented code. Please check for more commented codes especially in your `app/models` directory.

2020-12-06 07:09 UTC, tirthajyoti-ghosh approved these changes
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-12-06 15:12 UTC, merged